#' Function: Parse the tub files generated by gettub6.trx
#' Input: tub file path
#' Output: A data frame that contains tub data by head / zone
#' Algorithm: Read tub file -> Locate lines of head number -> Parse head/zone/DAC/Tub by line offset


parse_tub <- function(tubFile){
  text <- readLines(tubFile,warn = FALSE)
  tubIdx = grep("Head            :",text)
  data = list(Head=numeric(0),Zone=numeric(0),TubName=character(0),SelectedDac=numeric(0),TubData=list())
  for (idx in tubIdx){
    temp = strsplit(text[idx],":")
    hd = as.numeric(gsub(" ","",temp[[1]][2]))

    temp = strsplit(text[idx+1],":")
    zn = as.numeric(gsub(" ","",temp[[1]][2]))

    temp = strsplit(text[idx+2],":")
    tubName = gsub(" ","",temp[[1]][2])

    temp = strsplit(text[idx+16],":")
    temp = gsub(" ","",temp[[1]][2])
    selectedDac = strtoi(gsub("H","",temp),16L)

    tubData = data.frame()
    i=21
    while(text[idx+i]!="" & idx+i<=length(text)){
      temp = strsplit(text[idx+i],"H")
      temp = gsub(" ","",temp[[1]][1:3])
      temp = strtoi(temp,16L)
      temp = data.frame(DAC=temp[1],COUNT=temp[2],VALUE=temp[3])
      tubData = rbind(tubData,temp)
      i = i+1
    }

    temp = data.frame(Head=hd,Zone=zn,TubName=tubName,SelectedDac=selectedDac)
    temp$TubData = list(tubData)
    data = rbind(data,temp)
  }
  return(data)
}
